### ISSUE TITLE
Error when running in QEMU

### ISSUE THREAD

**Issue by mcplayeraz** [ZhouZhihaos/Powerint-DOS-386#11]
I used make to build img file in **develop** branch, then ran it in **QEMU**. 
But I met some situation like the following pictures. 
![p1](https://github.com/ZhouZhihaos/Powerint-DOS-386/assets/106917936/82ca0217-1552-4e15-b221-f2425d9cf908)
![p2](https://github.com/ZhouZhihaos/Powerint-DOS-386/assets/106917936/e7248efe-e0c1-40a9-afca-3f0bb1c89bdd)
Could you help fix it up?

**Comment by ZhouZhihaos** [comment]
These are some old problems,and now I have already fixed it up.
We refactor the gui mode and it's running well now.
I will update the new version recently.

**Comment by mcplayeraz** [comment]
I saw it just now...
And I think Chinese is a better choice to avoid some translating work.


Java Rick
________________________________

**Comment by ZhouZhihaos** [comment]
Are you a Chinese man?
If you are, why do we use English to communicate instead of Chinese? hahaha...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhouZhihaos/Powerint-DOS-386"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月18日(星期二) 晚上7:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhouZhihaos/Powerint-DOS-386] Error when running in QEMU (Issue #11)





 I saw it just now... 
 And I think Chinese is a better choice to avoid some translating work. 
 
 
 Java Rick 
 ________________________________

**Comment by mcplayeraz** [comment]
I meant I am in a 223-person group.

Java Rick
________________________________

**Comment by ZhouZhihaos** [comment]
Oh, what is your name in the QQ group? I wonder that.
Your English is much better than me, but both we are chinese, 为什么不用汉语交流呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhouZhihaos/Powerint-DOS-386"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月18日(星期二) 晚上7:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhouZhihaos/Powerint-DOS-386] Error when running in QEMU (Issue #11)





 I meant I am in a 223-person group. 
 
 Java Rick 
 ________________________________

**Comment by mcplayeraz** [comment]
But in fact your vocabulary is wider than me...
May I add you in QQ?

Java Rick
________________________________

**Comment by ZhouZhihaos** [comment]
Of course,my QQ id is 2901197932.
To be honest, I'm just a 14-year-old boy and my vocabulary&nbsp;comes from English book, is not wider than you...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhouZhihaos/Powerint-DOS-386"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月20日(星期四) 凌晨5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhouZhihaos/Powerint-DOS-386] Error when running in QEMU (Issue #11)





 But in fact your vocabulary is wider than me... 
 May I add you in QQ? 
 
 Java Rick 
 ________________________________

**Comment by mcplayeraz** [comment]
... I am just ask for a permission, not the qq number. I will add you at once.
By the way, I am born in 2009.

Java Rick
________________________________
